use_frameworks!

target 'ZCatalyst_Example' do
  pod 'ZCatalyst', :path => '../'
  pod 'ZohoPortalAuth', '0.0.3'
  pod 'Apptics-SDK/Core', '1.0.0'
   pod 'Apptics-SDK/CrashKit', '1.0.0'
   pod 'Apptics-SDK/Scripts', '1.0.0'
   pod 'AppticsRateUs', '1.0.0'
   pod 'AppticsFeedbackKit', '1.0.0'

  target 'ZCatalyst_Tests' do
    inherit! :search_paths
  end

end
