use_frameworks!


#source 'https://git.csez.zohocorpin.com/zoho/zohopodspecs.git'

target 'ZCatalyst_Example' do
  pod 'ZCatalyst', :path => '../'
  pod 'ZohoPortalAuth', '0.0.3'


  target 'ZCatalyst_Tests' do
    inherit! :search_paths
  end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
  end
end

end
